### ISSUE TITLE
答疑解惑

### ISSUE THREAD

**Issue by secjgrs** [1665169869/Message-Push-ScriptCat#1]
纯小白，作业可以教一下怎么应用嘛，拜托拜托

**Comment by 1665169869** [comment]
安装chrome扩展[脚本猫](https://docs.scriptcat.org/docs/dev/config/)
然后[安装脚本猫脚本](https://scriptcat.org/script-show-page/1101)
就ok了

**Comment by secjgrs** [comment]
好的非常感谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月18日(星期天) 凌晨0:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1665169869/scriptcat-push-weixin] 答疑解惑 (Issue #1)





 
安装chrome扩展脚本猫
 然后安装脚本猫脚本
 就ok了
